# Generated by Django 4.1.7 on 2023-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('challenge', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=42)),
            ],
        ),
    ]
